service: reddelete

provider:
  name: aws
  runtime: python3.7
  region: us-west-1
  stage: prod

functions:
  reddelete:
    handler: handler.run
    dashboard: true
    events:
      # Invoke Lambda function periodically
      - schedule: rate(6 hours)
    environment:
      REDDIT_CLIENT_ID:
      REDDIT_CLIENT_SECRET:
      REDDIT_USERNAME:
      REDDIT_PASSWORD:
      DELETE_THRESHOLD: 0

plugins:
  - serverless-python-requirements
  - serverless-plugin-cloudwatch-dashboard

dashboard:
  lambda:
    metrics: [ Duration, Errors, Invocations, Throttles ]
    stats: [p99, p95, p90, p50]
    enabled: true

custom:
  pythonRequirements:
    dockerizePip: non-linux