service: reddelete

frameworkVersion: ">=1.2.0 <2.0.0"

provider:
  name: aws
  runtime: python3.7
  region: us-west-1
  stage: prod

functions:
  reddelete:
    handler: handler.run
    events:
      # Invoke Lambda function periodically
      - schedule: rate(6 hours)
    environment:
      REDDIT_CLIENT_ID:
      REDDIT_CLIENT_SECRET:
      REDDIT_USERNAME:
      REDDIT_PASSWORD:
      DELETE_THRESHOLD: 0

plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    dockerizePip: non-linux